Hw10 program optimization
BorisPlus/OTUS-Go-2023-03 pull request #12
Opened 2023-07-16 22:42 UTC by BorisPlus

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-07-17 04:41 UTC, agneum requested changes
Спасибо за вариант решения. 
В целом выглядит хорошо, хотя немного сложнее изначального варианта с точки зрения поддержки. Однако к решению есть существенное замечание (см. комментарии и частые ошибки).

Итого: 6 баллов из 10. Возвращаю задачу на доработку

2023-07-17 04:41 UTC, agneum commented on hw10_program_optimization/stats.go
> +	domainStat *DomainStat,
Мапа - ссылочный тип, не нужно использовать указатель с мапой

2023-07-17 04:41 UTC, agneum commented on hw10_program_optimization/stats.go
> +	domainAtEmailRegexp := fmt.Sprintf(`@(\w+\.%s)`, domain)
Для этой задачи можно использовать https://pkg.go.dev/strings#HasSuffix вместо regexp, чтобы определить, что строка заканчивается на искомое доменное имя

2023-07-17 04:41 UTC, agneum commented on hw10_program_optimization/stats.go
> +			dataChannel <- domainAtLowercase
Если в другом поле (не `email`) в строке будет адрес электронной почты, то он будет ошибочно учтён

см. частые ошибки
https://github.com/BorisPlus/OTUS-Go-2023-03/tree/hw10_program_optimization/hw10_program_optimization#%D1%87%D0%B0%D1%81%D1%82%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8

Рекомендую использовать альтернативные json-парсеры (jsoniter, fastjson, easyjson и т.д.), **если** производительности стандартного недостаточно

2023-07-17 04:41 UTC, agneum commented on hw10_program_optimization/REPORT.md
> +### sync.Map
syncMap имеет смысл только на системах с высокими требованиями к производительности и с большим количеством ядер процессора (32+)

2023-07-17 12:08 UTC, BorisPlus commented on hw10_program_optimization/stats.go
> +	domainAtEmailRegexp := fmt.Sprintf(`@(\w+\.%s)`, domain)
Хорошо, значит имеем абсолютное доверие к содержанию поля Email. Договорились, я переделаю.

2023-07-17 12:15 UTC, BorisPlus commented on hw10_program_optimization/REPORT.md
> +### sync.Map
Учту на практике на проде, спасибо! Суть в том, что я искал источник невалидных данных. Пробовал все варианты, так как не понимал, почему в ключах левые строки. Так и не понял.

2023-07-17 12:20 UTC, BorisPlus commented on hw10_program_optimization/stats.go
> +			dataChannel <- domainAtLowercase
Хорошо, значит имеем абсолютное доверие к данным в принципе и считаем исключительно по полю Email. Это конкретизирует условие задачи и сужает пространство для маневра. Переделаю.

2023-07-17 12:23 UTC, BorisPlus commented on hw10_program_optimization/stats.go
> +	domainStat *DomainStat,
Да, странно, что так тут написал. В других вариантах я сделал по значению. В принципе, кажется, без разницы для Map как ее передавать для изменения ее внутренностей?

2023-07-21 11:07 UTC, agneum commented on hw10_program_optimization/stats_common_optimization_test.go
> +	TemplateCommonGetDomainStatTimeAndMemory(t, GetDomainStatInitial)
Предлагаю убрать запуск initial-функции из тестов, иначе пайплайн не проходит

2023-07-25 01:09 UTC, agneum approved these changes
Спасибо за правки. Принято. 
Итого: 10 баллов из 10

2023-07-26 19:36 UTC, merged