Hw03 frequency analysis
BorisPlus/OTUS-Go-2023-03 pull request #4
Opened 2023-04-21 01:04 UTC by BorisPlus

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-04-23 19:17 UTC, agneum requested changes
Спасибо за выполненное задание. 
Хорошее решение, но выглядит немного переусложнённым.

Поскольку пайплайн не пройден из-за замечаний линтера, возвращаю задачу на доработку.
Итого: 6 баллов из 10

2023-04-23 19:17 UTC, agneum commented on hw03_frequency_analysis/top.go
> +var LIMIT = 10
Для неизменяемых значений рекомендовал бы использовать константу вместо глобальной переменной. Если не предполагается использовать это значение вне пакета, то лучше сделать его неэкспортируемым.

Кстати, по всей видимости, это значение сейчас никак не используется.

2023-04-23 19:17 UTC, agneum commented on hw03_frequency_analysis/top.go
> +// OK. StringSpliter("qwe asd zxc qwe") return expected ["qwe" "asd" "zxc" "qwe"].
Комментарий функции следует начинать с названия, чтобы текст комментария был обработан GoDoc. 
Обычно тест-кейсы не принято указывать в комментарии. На мой взгляд, файла с тестами достаточно, и нет необходимости дублировать тест-кейсы в коде программы.

Дополнительные рекомендации по комментированию кода можно найти в документации: https://go.dev/doc/comment#func

2023-04-23 19:17 UTC, agneum commented on hw03_frequency_analysis/top.go
> +func StringSpliter(str string) []string {
Рекомендую использовать функции стандартной библиотеки https://pkg.go.dev/strings#Fields

2023-04-23 19:17 UTC, agneum commented on hw03_frequency_analysis/top.go
> +type DistributionOfMappedWord struct {
Использование структуры выглядит избыточно, можно работать с мапой, код будет выглядеть чуть проще.

2023-04-23 19:17 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		if stringWord == "" {
Исходя из кода предыдущей функции `stringWord` не может быть пустой строкой

2023-04-23 19:17 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	min := func(x, y uint) uint {
Поскольку функция вызывается только один раз, предложил бы заменить её на условие

2023-04-23 19:17 UTC, agneum commented on hw03_frequency_analysis/top_test.go
> +	"fmt"
Рекомендую отформатировать файл по стандарту линтера, чтобы пайплайн был пройден

2023-04-23 20:50 UTC, BorisPlus commented on hw03_frequency_analysis/top.go
> +// OK. StringSpliter("qwe asd zxc qwe") return expected ["qwe" "asd" "zxc" "qwe"].
Документацию сгененрировал, мне понравилось, приложу к отчету. Спасибо. В программе курса, кстати, я не помню ее. А вещь полезная. Спасибо.

2023-04-23 21:13 UTC, BorisPlus commented on hw03_frequency_analysis/top.go
> +type DistributionOfMappedWord struct {
Ok, отказался  от структуры, проименовав ее как тип `type DistributionOfMappedWord map[string]uint`. Но потом отказался и от типа. Хотелось оставить так, чтоб забыть о том, как он там выглядит внутри, просто ссылаясь на тип, и понимать по тексту ее функциональное назначение. Оставлю так без ничего, но с типом было, наверное, когнитивно выгоднее.

2023-04-23 21:24 UTC, BorisPlus commented on hw03_frequency_analysis/top.go
> +		if stringWord == "" {
Согласен, в контексте их последовательного вызова. Но теперь, отказавшись от DistributionOfMappedWord в угоду map[string]uint, это ветвление нужно для недопущения передачи в GetAsSortedStructWords() внешним потребителем мапы, содержащей пустую строку как "слово". Оставил.

2023-04-23 21:43 UTC, BorisPlus commented on hw03_frequency_analysis/top.go
> +	min := func(x, y uint) uint {
Да, действительно, так изящнее

```go
if uint(len(structWords)) < limit {
	limit = uint(len(structWords))
}
return structWords[:limit]
```

2023-04-23 21:53 UTC, BorisPlus commented on hw03_frequency_analysis/top.go
> +var LIMIT = 10
Больше его нету

2023-04-23 22:11 UTC, BorisPlus commented on hw03_frequency_analysis/top.go
> +func StringSpliter(str string) []string {
Может показаться теперь излишне атомарным, но мне видится, что оно таким и должно быть. Так как следующий этап работает с подсчетом частоты слов по слайсу, а то, какая функция ему даст этот слайс, не важно. В другом варианте слова из того же самого текста будут формироваться по другой логике\правилу, и чтоб не переписывать подсчет частоты, нужно их просто подать на вход уже реализованной функции подсчета частоты по слайсу слов.
```
func StringSpliter(str string) []string {
	return strings.Fields(str)
}
```

2023-04-23 22:12 UTC, BorisPlus commented on hw03_frequency_analysis/top_test.go
> +	"fmt"
Странно, мне казалось, я запускал локально `golangci-lint run --out-format=github-actions`, и он был чист.

2023-04-23 22:15 UTC, BorisPlus commented
Top10 - функция с заданной в домашнем задании сигнатурой.

Реализована в виде последовательного вызова разработанных методов,
максимально декомпозирующих исходную задачу на отдельные атомарные этапы,
без дублирования кода.
Сейчас мне видится, что она не содержит в себе ничего лишнего, необходимого сверх решения поставленной задачи.

2023-04-23 22:16 UTC, BorisPlus commented
Спасибо Вам огромное за проверку!

2023-04-24 00:12 UTC, agneum approved these changes
Спасибо за правки, отличная работа!
Итого: 10 баллов из 10. Принято

2023-04-24 00:12 UTC, agneum commented on hw03_frequency_analysis/top.go
> +func StringSpliter(str string) []string {
Если нужны специфичные правила того, что считать разделителем, то можно использовать https://pkg.go.dev/strings#FieldsFunc

2023-04-27 19:26 UTC, merged